// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlKxRi8Zg9FUQJJ3ZbS2apM3_tksKEEmw',
    appId: '1:107958687810:web:625f1c47aac030259735db',
    messagingSenderId: '107958687810',
    projectId: 'fisherspace-63501',
    authDomain: 'fisherspace-63501.firebaseapp.com',
    storageBucket: 'fisherspace-63501.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsHQbsMsyAhHPaK1P_Se10k5TfERh_c6A',
    appId: '1:107958687810:android:29dc7c70414673939735db',
    messagingSenderId: '107958687810',
    projectId: 'fisherspace-63501',
    storageBucket: 'fisherspace-63501.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWAgOs3D9Tvz75l2qODkDKRdY0UR5okzk',
    appId: '1:107958687810:ios:d7f26bd25028d78d9735db',
    messagingSenderId: '107958687810',
    projectId: 'fisherspace-63501',
    storageBucket: 'fisherspace-63501.firebasestorage.app',
    iosClientId: '107958687810-3ge1d1oe4sv8cumj9gm5vbvap8mdmh44.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWAgOs3D9Tvz75l2qODkDKRdY0UR5okzk',
    appId: '1:107958687810:ios:d7f26bd25028d78d9735db',
    messagingSenderId: '107958687810',
    projectId: 'fisherspace-63501',
    storageBucket: 'fisherspace-63501.firebasestorage.app',
    iosClientId: '107958687810-3ge1d1oe4sv8cumj9gm5vbvap8mdmh44.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlKxRi8Zg9FUQJJ3ZbS2apM3_tksKEEmw',
    appId: '1:107958687810:web:623b48c1e991e9d99735db',
    messagingSenderId: '107958687810',
    projectId: 'fisherspace-63501',
    authDomain: 'fisherspace-63501.firebaseapp.com',
    storageBucket: 'fisherspace-63501.firebasestorage.app',
  );
}
